import Head from "next/head";
import { Inter } from "@next/font/google";
import { useEffect, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

const getRandomItems = (length) => (array) => {
  return array
    .sort(() => Math.round(Math.random() * -1))
    .slice(0, length ?? array.length);
};

const get2RandomItems = getRandomItems(2);

export default function Home() {
  const [scorers, setScorers] = useState([]);
  const [twoScorers, setTwoScorers] = useState([]);

  useEffect(() => {
    const fetchData = async () => {
      const res = await fetch("https://goals-hol.brucolon.workers.dev/scorers");
      const scorersData = await res.json();
      setScorers(scorersData);
    };
    fetchData();
  }, []);

  if (scorers.length === 0) return null;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <section className="option-one">
          <h1>{scorers[0].name}</h1>
          <span>has</span>
          <h1>{scorers[0].goals}</h1>
          <span>goals</span>
        </section>
        <section className="option-two">
          <h1>{scorers[1].name}</h1>
          <span>has</span>
          <h1>{scorers[1].goals}</h1>
          <span>goals than</span>
        </section>
      </main>
      <style jsx>{`
        main {
          padding: 0;
          width: 100%;
          height: 100vh;
          display: flex;
          flex-direction: row;
          color: white;
        }
        section {
          display: flex;
          align-items: center;
          justify-content: center;
          flex-direction: column;
          width: 100%;
          height: 100%;
        }
        h1 {
          color: white;
          position: relative;
        }
        .option-one {
          background: red;
          background-image: url(${scorers[0].imgURL});
          background-repeat: no-repeat;
          background-position: center;
          background-size: contain;
        }
        .option-one:before {
          content: " ";
          position: absolute;
          top: 0;
          bottom: 0;
          left: 0;
          right: 0;
          background-color: rgba(0, 0, 0, 0.6);
        }
        .option-two {
          background: blue;
          background-image: url(${scorers[1].imgURL});
          background-repeat: no-repeat;
          background-position: center;
          background-size: contain;
        }
      `}</style>
    </>
  );
}
